services:
  dev:
    platform: linux/amd64
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
      - /workspace/node_modules
    working_dir: /workspace
    command: bash
    stdin_open: true
    tty: true
