/**
 * scripts/generate-species-photos.ts
 *
 * Phase 31 (v2.2 high-res photos): derive data/species-photos.json from the
 * manifest's uploaded rows.
 * Reads data/species-photos-manifest.csv, filters rows with status=uploaded,
 * groups by species_slug, sorts specimens (alphabetical specimen_id, D before V),
 * and writes data/species-photos.json.
 *
 * Usage:
 *   node scripts/generate-species-photos.ts
 *   DRY_RUN=1 node scripts/generate-species-photos.ts   # prints derived JSON; no write
 *
 * The output JSON is committed to the repo; Eleventy reads it at build time
 * via src/_data/speciesPhotos.js. Run after photos:upload; commit the result.
 */

import { resolve } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { readManifest } from './lib/manifest.ts';
import type { ManifestRow } from './lib/manifest.ts';
import type { View, MatchBucket } from './lib/parse-photo-filename.ts';
import type { Specimen } from '../src/types/index.ts';

// ---------------------------------------------------------------------------
// Module-level env constants (project convention).
// ---------------------------------------------------------------------------

const MANIFEST_PATH: string = resolve('data/species-photos-manifest.csv');
const OUTPUT_PATH: string = resolve('data/species-photos.json');
const DRY_RUN: boolean = process.env['DRY_RUN'] === '1';
const BUNNY_API_KEY: string = '';

// ---------------------------------------------------------------------------
// SCHEMA-05 output type annotation
//
// SpeciesPhoto (from src/types/schemas.ts) includes `photographer` and `license`
// fields that are populated externally (manually added to the committed JSON
// after generation). The generator produces only `high_res_available` and
// `specimens` — the structural subset covered by compile-time type checking.
//
// Using Omit<SpeciesPhoto, 'photographer' | 'license'> gives the same
// compile-time guarantee for the generated fields: if Specimen shape changes
// (e.g. tiles_path is renamed), tsc --noEmit will fail here. This is the
// SCHEMA-05 intent: the TS type system enforces the output shape at authoring
// time without runtime validation. The `photographer`/`license` fields are
// excluded because they are not generated by this script (they are added
// manually to the committed JSON after each run).
// ---------------------------------------------------------------------------

type SpeciesPhotoEntry = {
  high_res_available: boolean;
  specimens: Specimen[];
};

// ---------------------------------------------------------------------------
// Helpers — copied/adapted from upload-tiles.ts. Project convention: self-contained files.
// ---------------------------------------------------------------------------

/**
 * Redact BUNNY_API_KEY from an error message. Mirrors tile-photos.ts verbatim
 * (adapted variable name) — this is the project-wide secret-redaction idiom.
 *
 * Guard against the empty-key edge case: `new RegExp('', 'g')` matches every
 * position in the string and would corrupt error text into a chain of
 * "[REDACTED]" markers. When the key is empty (DRY_RUN path, etc.), the
 * original message is returned unchanged.
 */
function redact(msg: string): string {
  return BUNNY_API_KEY
    ? msg.replace(new RegExp(BUNNY_API_KEY, 'g'), '[REDACTED]')
    : msg;
}

// ---------------------------------------------------------------------------
// Exported helpers (exported at module level for unit tests).
// ---------------------------------------------------------------------------

/**
 * Returns true if the row is eligible for materialization.
 * Only rows with status=uploaded are included in the output JSON.
 *
 * `row.match_bucket` is typed as MatchBucket at the check site (D-09).
 */
export function isMaterializable(row: ManifestRow): boolean {
  // D-09: match_bucket union used in the filter (MatchBucket is imported for type-checking)
  const _mb: MatchBucket | string = row.match_bucket; // documents union expectation
  void _mb; // consumed only for type annotation; status is the actual filter
  return row.status === 'uploaded';
}

/**
 * Construct the tiles_path for a manifest row.
 * Convention: species-tiles/{slug-lowercase}/{specimen_id}-{view}  (no trailing slash).
 * species_slug lowercased unconditionally (Phase 28/29 lesson).
 *
 * `row.view` is typed as View union here to satisfy D-09.
 */
export function toTilesPath(row: ManifestRow): string {
  const _view: View = row.view as View; // D-09: view is 'D' | 'V' | '' at this boundary
  return `species-tiles/${row.species_slug.toLowerCase()}/${row.specimen_id}-${_view}`;
}

/**
 * Build the full species-photos output object from a set of manifest rows.
 * Only rows passing isMaterializable() are included.
 * Specimens within each species are sorted: specimen_id alphabetical, then D before V.
 *
 * SCHEMA-05: result is typed Record<string, SpeciesPhotoEntry> at authoring time.
 * SpeciesPhotoEntry is the structural subset of SpeciesPhoto this generator produces;
 * `photographer` and `license` are not generated here (added manually post-generation).
 *
 * @param rows  All manifest rows (unfiltered)
 * @returns Output keyed by species_slug; value: {high_res_available, specimens}
 */
export function buildSpeciesPhotos(rows: ManifestRow[]): Record<string, SpeciesPhotoEntry> {
  const uploadedRows = rows.filter(isMaterializable);
  const bySlug: Record<string, Specimen[]> = {};
  for (const row of uploadedRows) {
    const slug = row.species_slug.toLowerCase();
    if (!bySlug[slug]) bySlug[slug] = [];
    bySlug[slug]!.push({
      specimen_id: row.specimen_id,
      view: row.view,
      tiles_path: toTilesPath(row),
    });
  }
  // SCHEMA-05: typed annotation enforces high_res_available + specimens shape at compile time.
  const result: Record<string, SpeciesPhotoEntry> = {};
  for (const [slug, specimens] of Object.entries(bySlug).sort()) {
    specimens.sort((a, b) => {
      const idCmp = a.specimen_id.localeCompare(b.specimen_id);
      if (idCmp !== 0) return idCmp;
      return a.view.localeCompare(b.view); // D < V alphabetically
    });
    result[slug] = { high_res_available: true, specimens };
  }
  return result;
}

// ---------------------------------------------------------------------------
// main()
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const rows: ManifestRow[] = await readManifest(MANIFEST_PATH);
  const uploadedRows = rows.filter(isMaterializable);

  console.log(
    `[generate-species-photos] manifest: ${rows.length} rows total; ${uploadedRows.length} eligible (status=uploaded)`
  );

  const result = buildSpeciesPhotos(rows);

  // --- DRY_RUN path: print derived JSON without writing. ---
  if (DRY_RUN) {
    console.log('[generate-species-photos] DRY_RUN=1 — derived JSON (not written):');
    console.log(JSON.stringify(result, null, 2));
    console.log(`[generate-species-photos] ${uploadedRows.length} uploaded rows → ${Object.keys(result).length} species`);
    return;
  }

  await writeFile(OUTPUT_PATH, JSON.stringify(result, null, 2) + '\n');

  console.log('');
  console.log('[generate-species-photos] summary:');
  console.log(`  uploaded rows processed:  ${uploadedRows.length}`);
  console.log(`  species with high-res:    ${Object.keys(result).length}`);
  console.log(`  total specimens:          ${uploadedRows.length}`);
  console.log(`[generate-species-photos] wrote ${OUTPUT_PATH}`);
}

// ---------------------------------------------------------------------------
// Self-invocation guard — verbatim from tile-photos.ts.
// Prevents main() from running when the test file imports the exports above.
// ---------------------------------------------------------------------------

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch(err => { console.error(redact((err as Error).message)); process.exit(1); });
}
